using UnityEditor;
using UnityEngine;

/// <summary>
/// Builds five low-poly wall paintings for hallway decoration. Each painting
/// is a wooden frame (backing box) + a Quad textured with a 128x128,
/// point-filtered, procedurally-generated abstract image — deliberately
/// simple/blocky (Minecraft-painting style), so there is no copyright
/// concern: the pixels are generated by this script, not sourced from any
/// existing artwork. Deployed to Resources/Prefabs/AssetContents (same
/// convention as the other Generate*Prop.cs scripts in this folder).
/// Menu: Tools / Procedural Cities / Generate Painting Props
/// </summary>
public static class GeneratePaintingProps
{
    private const string PkgRoot = "Packages/dev.z3nth10n.proceduralcities.import";
    private const string PrefabDir = PkgRoot + "/Resources/Prefabs/AssetContents";
    private const string MatDir = PkgRoot + "/Models/LowPoly/Materials";
    private const string TexDir = PkgRoot + "/Models/LowPoly/Textures";

    private const int Size = 128;
    private const float PaintingWidth = 0.50f;
    private const float PaintingHeight = 0.35f;

    [MenuItem("Tools/Procedural Cities/Generate Painting Props")]
    public static void Generate()
    {
        EnsureFolders();

        var matFrame = GetSharedMat("LP_Painting_Frame", new Color(0.24f, 0.15f, 0.08f), 0.05f, 0.25f);

        SaveOne("Painting1", "LP_Painting_Tex1", matFrame, SunsetStripes);
        SaveOne("Painting2", "LP_Painting_Tex2", matFrame, MountainSilhouette);
        SaveOne("Painting3", "LP_Painting_Tex3", matFrame, ColorBlocks);
        SaveOne("Painting4", "LP_Painting_Tex4", matFrame, OceanWaves);
        SaveOne("Painting5", "LP_Painting_Tex5", matFrame, StarryNightBlocks);

        AssetDatabase.SaveAssets();
        AssetDatabase.Refresh();
        Debug.Log($"[GeneratePaintingProps] Saved 5 painting prefabs under {PrefabDir}");
    }

    private static void SaveOne(
        string prefabName, string texName, Material matFrame, System.Func<Texture2D> paint)
    {
        var tex = paint();
        tex.name = texName;
        var texPath = $"{TexDir}/{texName}.asset";
        var existingTex = AssetDatabase.LoadAssetAtPath<Texture2D>(texPath);
        if (existingTex != null)
            AssetDatabase.DeleteAsset(texPath);
        AssetDatabase.CreateAsset(tex, texPath);

        var matPicture = new Material(
            Shader.Find("Universal Render Pipeline/Unlit") ?? Shader.Find("Unlit/Texture"))
        {
            name = texName + "_Mat",
        };
        matPicture.mainTexture = tex;
        var matPath = $"{MatDir}/{texName}_Mat.mat";
        var existingMat = AssetDatabase.LoadAssetAtPath<Material>(matPath);
        if (existingMat != null)
            AssetDatabase.DeleteAsset(matPath);
        AssetDatabase.CreateAsset(matPicture, matPath);

        var root = BuildFrame(prefabName, matFrame, matPicture);
        PrefabUtility.SaveAsPrefabAsset(root, $"{PrefabDir}/{prefabName}.prefab");
        Object.DestroyImmediate(root);
    }

    private static GameObject BuildFrame(string rootName, Material matFrame, Material matPicture)
    {
        var root = new GameObject(rootName);

        var backing = GameObject.CreatePrimitive(PrimitiveType.Cube);
        Object.DestroyImmediate(backing.GetComponent<Collider>());
        backing.name = "Frame";
        backing.transform.SetParent(root.transform, false);
        backing.transform.localScale = new Vector3(PaintingWidth, PaintingHeight, 0.03f);
        backing.GetComponent<MeshRenderer>().sharedMaterial = matFrame;

        var picture = GameObject.CreatePrimitive(PrimitiveType.Quad);
        Object.DestroyImmediate(picture.GetComponent<Collider>());
        picture.name = "Picture";
        picture.transform.SetParent(root.transform, false);
        picture.transform.localPosition = new Vector3(0, 0, -0.016f);
        picture.transform.localScale = new Vector3(PaintingWidth - 0.05f, PaintingHeight - 0.05f, 1f);
        picture.GetComponent<MeshRenderer>().sharedMaterial = matPicture;

        var collider = root.AddComponent<BoxCollider>();
        collider.size = new Vector3(PaintingWidth, PaintingHeight, 0.05f);

        return root;
    }

    // ── Procedural 128x128 abstract paintings ───────────────────────────

    private static Texture2D NewTex()
    {
        var tex = new Texture2D(Size, Size, TextureFormat.RGBA32, false)
        {
            filterMode = FilterMode.Point,
            wrapMode = TextureWrapMode.Clamp,
        };
        return tex;
    }

    private static Texture2D SunsetStripes()
    {
        var tex = NewTex();
        var top = new Color(1.0f, 0.55f, 0.20f);
        var mid = new Color(0.75f, 0.30f, 0.45f);
        var bottom = new Color(0.20f, 0.12f, 0.30f);
        for (var y = 0; y < Size; y++)
        {
            var t = y / (float)(Size - 1);
            var c = t < 0.5f
                ? Color.Lerp(bottom, mid, t * 2f)
                : Color.Lerp(mid, top, (t - 0.5f) * 2f);
            for (var x = 0; x < Size; x++)
                tex.SetPixel(x, y, c);
        }

        // Simple sun disc.
        var cx = Size * 0.5f;
        var cy = Size * 0.35f;
        var r = Size * 0.14f;
        for (var y = 0; y < Size; y++)
            for (var x = 0; x < Size; x++)
                if ((x - cx) * (x - cx) + (y - cy) * (y - cy) < r * r)
                    tex.SetPixel(x, y, new Color(1f, 0.92f, 0.6f));

        tex.Apply();
        return tex;
    }

    private static Texture2D MountainSilhouette()
    {
        var tex = NewTex();
        var skyTop = new Color(0.55f, 0.70f, 0.85f);
        var skyBottom = new Color(0.95f, 0.85f, 0.65f);
        for (var y = 0; y < Size; y++)
        {
            var t = y / (float)(Size - 1);
            var c = Color.Lerp(skyBottom, skyTop, t);
            for (var x = 0; x < Size; x++)
                tex.SetPixel(x, y, c);
        }

        // Moon.
        DrawDisc(tex, Size * 0.78f, Size * 0.80f, Size * 0.07f, new Color(0.98f, 0.98f, 0.92f));

        // Two overlapping triangular ridges.
        var dark = new Color(0.10f, 0.10f, 0.14f);
        var darker = new Color(0.05f, 0.05f, 0.08f);
        for (var x = 0; x < Size; x++)
        {
            var ridge1 = Mathf.Abs(x - Size * 0.35f) * 0.55f;
            var peak1 = Size * 0.30f + ridge1;
            var ridge2 = Mathf.Abs(x - Size * 0.75f) * 0.70f;
            var peak2 = Size * 0.42f + ridge2;
            for (var y = 0; y < Size; y++)
            {
                if (y > peak2) tex.SetPixel(x, y, darker);
                if (y > peak1) tex.SetPixel(x, y, dark);
            }
        }

        tex.Apply();
        return tex;
    }

    private static Texture2D ColorBlocks()
    {
        var tex = NewTex();
        for (var y = 0; y < Size; y++)
            for (var x = 0; x < Size; x++)
                tex.SetPixel(x, y, new Color(0.92f, 0.90f, 0.85f));

        var rng = new System.Random(1337);
        var palette = new[]
        {
            new Color(0.85f, 0.15f, 0.12f),
            new Color(0.95f, 0.80f, 0.10f),
            new Color(0.10f, 0.30f, 0.70f),
        };
        for (var i = 0; i < 6; i++)
        {
            var bx = rng.Next(0, Size - 30);
            var by = rng.Next(0, Size - 30);
            var bw = rng.Next(20, 45);
            var bh = rng.Next(20, 45);
            var col = palette[rng.Next(palette.Length)];
            for (var y = by; y < Mathf.Min(by + bh, Size); y++)
                for (var x = bx; x < Mathf.Min(bx + bw, Size); x++)
                    tex.SetPixel(x, y, col);
        }

        // Thick black grid lines for a Mondrian look.
        var black = Color.black;
        var lineXs = new[] { Size / 4, Size / 2, (Size * 3) / 4 };
        var lineYs = new[] { Size / 3, (Size * 2) / 3 };
        foreach (var lx in lineXs)
            for (var y = 0; y < Size; y++)
                for (var w = -1; w <= 1; w++)
                    if (lx + w >= 0 && lx + w < Size)
                        tex.SetPixel(lx + w, y, black);
        foreach (var ly in lineYs)
            for (var x = 0; x < Size; x++)
                for (var w = -1; w <= 1; w++)
                    if (ly + w >= 0 && ly + w < Size)
                        tex.SetPixel(x, ly + w, black);

        tex.Apply();
        return tex;
    }

    private static Texture2D OceanWaves()
    {
        var tex = NewTex();
        var skyColor = new Color(0.75f, 0.88f, 0.92f);
        var deepWater = new Color(0.05f, 0.20f, 0.40f);
        var shallowWater = new Color(0.15f, 0.45f, 0.60f);
        var horizon = Size * 0.55f;

        for (var y = 0; y < Size; y++)
        {
            for (var x = 0; x < Size; x++)
            {
                if (y > horizon)
                {
                    var t = (y - horizon) / (Size - horizon);
                    var wave = Mathf.Sin((x + y * 1.5f) * 0.35f) * 3f;
                    var band = Mathf.PingPong((y + wave) * 0.4f, 1f);
                    var baseCol = Color.Lerp(shallowWater, deepWater, t);
                    var c = band > 0.85f ? Color.Lerp(baseCol, Color.white, 0.25f) : baseCol;
                    tex.SetPixel(x, y, c);
                }
                else
                {
                    tex.SetPixel(x, y, skyColor);
                }
            }
        }

        DrawDisc(tex, Size * 0.5f, Size * 0.42f, Size * 0.10f, new Color(1f, 0.95f, 0.75f));
        tex.Apply();
        return tex;
    }

    private static Texture2D StarryNightBlocks()
    {
        var tex = NewTex();
        var top = new Color(0.03f, 0.03f, 0.12f);
        var bottom = new Color(0.10f, 0.08f, 0.22f);
        for (var y = 0; y < Size; y++)
        {
            var t = y / (float)(Size - 1);
            var c = Color.Lerp(bottom, top, t);
            for (var x = 0; x < Size; x++)
                tex.SetPixel(x, y, c);
        }

        // Crescent moon: bright disc with a darker offset disc subtracted.
        DrawDisc(tex, Size * 0.72f, Size * 0.75f, Size * 0.11f, new Color(0.95f, 0.93f, 0.75f));
        DrawDisc(tex, Size * 0.78f, Size * 0.75f, Size * 0.10f, top);

        var rng = new System.Random(4242);
        for (var i = 0; i < 40; i++)
        {
            var x = rng.Next(0, Size);
            var y = rng.Next(0, Size);
            var b = 0.6f + (float)rng.NextDouble() * 0.4f;
            tex.SetPixel(x, y, new Color(b, b, b * 0.95f));
        }

        tex.Apply();
        return tex;
    }

    private static void DrawDisc(Texture2D tex, float cx, float cy, float r, Color color)
    {
        for (var y = 0; y < Size; y++)
            for (var x = 0; x < Size; x++)
                if ((x - cx) * (x - cx) + (y - cy) * (y - cy) < r * r)
                    tex.SetPixel(x, y, color);
    }

    private static void EnsureFolders()
    {
        if (!AssetDatabase.IsValidFolder(PkgRoot + "/Models/LowPoly"))
            AssetDatabase.CreateFolder(PkgRoot + "/Models", "LowPoly");
        if (!AssetDatabase.IsValidFolder(MatDir))
            AssetDatabase.CreateFolder(PkgRoot + "/Models/LowPoly", "Materials");
        if (!AssetDatabase.IsValidFolder(TexDir))
            AssetDatabase.CreateFolder(PkgRoot + "/Models/LowPoly", "Textures");
    }

    private static Material GetSharedMat(string name, Color color, float metallic, float smoothness)
    {
        var path = $"{MatDir}/{name}.mat";
        var existing = AssetDatabase.LoadAssetAtPath<Material>(path);
        if (existing != null)
            return existing;

        var shader = Shader.Find("Universal Render Pipeline/Lit") ?? Shader.Find("Standard");
        var mat = new Material(shader) { name = name, color = color };
        if (mat.HasProperty("_Metallic")) mat.SetFloat("_Metallic", metallic);
        if (mat.HasProperty("_Smoothness")) mat.SetFloat("_Smoothness", smoothness);
        else if (mat.HasProperty("_Glossiness")) mat.SetFloat("_Glossiness", smoothness);

        AssetDatabase.CreateAsset(mat, path);
        return mat;
    }
}
